package org.symphonyoss.integration.provisioning.properties;

import org.symphonyoss.integration.provisioning.service.KeyPairService;

/**
 * Properties keys and default values used by the component {@link KeyPairService}.
 * Created by rsanchez on 18/10/16.
 */
public class KeyPairProperties {

  /**
   * Property key to identify if the component should generate the user certificates.
   */
  public static final String GENERATE_CERTIFICATE = "generateCerts";

  /**
   * Property key to retrieve the signing certificate password.
   */
  public static final String SIGNING_CERT_PASSWORD = "signingCertPassword";

  /**
   * Property key to retrieve the user certificate password generated by the component.
   */
  public static final String OUTPUT_CERT_PASSWORD = "outputCertPassword";

  /**
   * ATLAS properties filename
   */
  public static final String INTEGRATION_PROPERTIES_FILE = "integration.properties";

  /**
   * Default keystore type.
   */
  public static final String DEFAULT_KEYSTORE_TYPE = "pkcs12";

}
